server:
  port: 8079
spring:
  application:
    name: spring-cloud-provider
  zipkin:
    base-url: http://localhost:9411
    sleuth:
      sampler:
        #采样率0-1之间，1代表全部采集
        probability: 1
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/spring_cloud?serverTimezone=GMT%2B8
    username: root
    password: 123456
mybatis:
  mapper-locations: classpath:mapperxml/*.xml
  type-aliases-package: com.lixiang.entity
logging:
  level:
    cn.itcast: debug
    org.springframework: debug
eureka:
  client:
    #    将自己加入eureka服务
    register-with-eureka: true
    #    是都从eureka抓取自己的注册信息，默认为true
    fetch-registry: true
    #    将服务注册到两个eureka服务器上
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/
  instance:
    #    自定义服务实例名
    instance-id: provider8079
    #    显示ip地址
    prefer-ip-address: true
    #eureka客户端向服务端发送心跳的时间间隔，单位为秒
    #    lease-renewal-interval-in-seconds: 1
    #eureka服务端在收到最后一次心跳后等待时间上限，默认30秒，超时即剔除服务
#    lease-expiration-duration-in-seconds: 2