#使用rabbitMQ需要先下载Erlang https://www.erlang.org/downloads
#然后再下载rabbitMQ https://github.com/rabbitmq/rabbitmq-server/releases/download/v3.9.13/rabbitmq-server-3.9.13.exe
#mq西在后需要在D:\guoqiang3\rabbitMQ\rabbitmq_server-3.9.13\sbin目录下执行 rabbitmq-plugins enable rabbitmq_management 命令启动管理功能
#安装后程序列表会出现可视化插件 点击 rabbitMQ -service start启动后访问localhost:15672 进入后默认用户名密码guest
server:
  port: 9901
spring:
  application:
    name: cloud-mq-bus
logging:
  level:
    cn.itcast: debug
    org.springframework: debug
eureka:
  client:
    #    将自己加入eureka服务
    register-with-eureka: true
    #    是都从eureka抓取自己的注册信息，默认为true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/
  instance:
#    自定义实例服务名
    instance-id: bus9901
#    显示ip
    prefer-ip-address: true