server:
  port: 9100
spring:
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
  application:
    name: nacos-provider-server
management:
  endpoints:
    web:
      exposure:
        include: '*'
