server:
  port: 8090
spring:
  application:
    name: consul-cloud-provider
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        service-name: ${spring.application.name}
logging:
  level:
    cn.itcast: debug
    org.springframework: debug