server:
  port: 8080
spring:
  application:
    name: spring-cloud-provider
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/spring_cloud?serverTimezone=GMT%2B8
    username: root
    password: 123456
mybatis:
  mapper-locations: classpath:mapperxml/*.xml
  type-aliases-package: com.lixiang.entity
logging:
  level:
    cn.itcast: debug
    org.springframework: debug
