server:
  port: 3344
spring:
  application:
    name: cloud-config-center
  cloud:
    config:
      server:
        git:
          uri: https://github.com/guo-q123/springcloud-demo-config.git
          search-paths:
            - springcloud-demo-config
        default-label: main
      #      默认分支
      label: main
    #rabbitMQ配置
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    #rabbitMQ相关配置，暴露bus刷新配置的端点
management:
  endpoints: #暴露bus刷新配置的断点
    web:
      exposure:
        include: "bus-refresh"
logging:
  level:
    cn.itcast: debug
    org.springframework: debug
eureka:
  client:
    #    将自己加入eureka服务
    register-with-eureka: true
    #    是否从eureka抓取自己的注册信息，默认为true
    fetch-registry: true
    service-url:
      #      http://eureka7001.com路径需要在C:\Windows\System32\drivers\etc下的host文件中添加
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/
#      defaultZone: http://localhost:7001/eureka/
