server:
  port: 8080
spring:
  application:
    name: spring-cloud-provider
  zipkin:
    base-url: http://localhost:9411
    sleuth:
      sampler:
        #采样率0-1之间，1代表全部采集
        probability: 1
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/spring_cloud?serverTimezone=GMT%2B8
    username: root
    password: 123456
mybatis:
  mapper-locations: classpath:mapperxml/*.xml
  type-aliases-package: com.lixiang.entity
logging:
  level:
    cn.itcast: debug
    org.springframework: debug
eureka:
  client:
    #    将自己加入eureka服务
    register-with-eureka: true
    #    是都从eureka抓取自己的注册信息，默认为true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/
  instance:
    #    自定义实例服务名
    instance-id: provider8080
    #    显示ip
    prefer-ip-address: true