server:
  port: 8084
spring:
  application:
    name: cloud-consumer-hystrix
logging:
  level:
    cn.itcast: debug
    org.springframework: debug
eureka:
  client:
    #    将自己加入eureka服务
    register-with-eureka: true
    #    是否从eureka抓取自己的注册信息，默认为true
    fetch-registry: true
    service-url:
      #      http://eureka7001.com路径需要在C:\Windows\System32\drivers\etc下的host文件中添加
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/
#      defaultZone: http://localhost:7001/eureka/

ribbon:
  #  指的是建立连接所用的时间，网络正常的情况下，两端连接所用的时间
  ReadTimeout: 2000
  #  指的是建立连接后从服务器读取到可用资源的时间
  ConnectTimeout: 2000

#开启 hystrix
feign:
  hystrix:
    enabled: true