server:
  port: 8803
spring:
  application:
    name: rabbit-stream-consumer
  cloud:
    stream:
      binders: #在此处配置要绑定的rabbitmq的服务信息
        defaultRabbit: #表示定义的名称，用于binding整合
          type: rabbit #消息组件类型
          environment: #表示rabbitmq的相关环境配置
            spring:
              #rabbitMQ配置
              rabbitmq:  #如果是使用的自己的服务器如（阿里云）来配置，则需要修改配置文件，将rabbitmq的配置信息移动到application.yml中的spring节点下 和cloud对齐
                host: localhost
                port: 5672
                username: guest
                password: guest

      bindings: #服务的整合处理
        input: #这个名字是一个通道的名称
          destination: studyExchange #表示要使用的exchange类型
          content-type: application/json #设置消息类型，本次为json文本则为text/plain
          binder: defaultRabbit #设置要绑定的消息服务的具体设置
logging:
  level:
    cn.itcast: debug
    org.springframework: debug
eureka:
  client:
    #    将自己加入eureka服务
    register-with-eureka: true
    #    是否从eureka抓取自己的注册信息，默认为true
    fetch-registry: true
    service-url:
      #      http://eureka7001.com路径需要在C:\Windows\System32\drivers\etc下的host文件中添加
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/
#      defaultZone: http://localhost:7001/eureka/
  instance:
    lease-renewal-interval-in-seconds: 2 #设置心跳的而时间间隔（默认三十秒）
    lease-expiration-duration-in-seconds: 5 #设置现在超过了五秒的间隔 默认是90秒
    instance-id: accept-8803.com
    prefer-ip-address: true #访问的路径变为ip地址
